apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-app
  namespace: a-maxmudov
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-app
  template:
    metadata:
      labels:
        app: hr-app
    spec:
      containers:
      - name: hr-app
        image: nginx:1.18
        ports:
        - containerPort: 80
