apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  namespace: a-maxmudov
  labels:
    name: nginx1
    project: practice
    author: a-maxmudov
spec:
  containers:
  - name: nginx1
    image: nginx:latest
    resources:
    ports:
      - containerPort: 80
